### Finding best model and hyperparameter tunning using GridSearchCV

#### For iris flower dataset in sklearn library, we are going to find out best model and hyperparameter using GridSearchCV

In [13]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score
iris = load_iris()

In [3]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x : iris.target_names[x])
df.head(2000)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [4]:
df[40:100]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
40                5.0               3.5                1.3               0.3   
41                4.5               2.3                1.3               0.3   
42                4.4               3.2                1.3               0.2   
43                5.0               3.5                1.6               0.6   
44                5.1               3.8                1.9               0.4   
45                4.8               3.0                1.4               0.3   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   
55                5.7               2.8                4.5               1.3   
56                6.3               3.3                4.7               1.6   
57                4.9               2.4                3.3               1.0   
58                6.6               2.9                4.6               1.3   
59                5.2               2.7                3.9               1.4   
60                5.0               2.0                3.5               1.0   
61                5.9               3.0                4.2               1.5   
62                6.0               2.2                4.0               1.0   
63                6.1               2.9                4.7               1.4   
64                5.6               2.9                3.6               1.3   
65                6.7               3.1                4.4               1.4   
66                5.6               3.0                4.5               1.5   
67                5.8               2.7                4.1               1.0   
68                6.2               2.2                4.5               1.5   
69                5.6               2.5                3.9               1.1   
70                5.9               3.2                4.8               1.8   
71                6.1               2.8                4.0               1.3   
72                6.3               2.5                4.9               1.5   
73                6.1               2.8                4.7               1.2   
74                6.4               2.9                4.3               1.3   
75                6.6               3.0                4.4               1.4   
76                6.8               2.8                4.8               1.4   
77                6.7               3.0                5.0               1.7   
78                6.0               2.9                4.5               1.5   
79                5.7               2.6                3.5               1.0   
80                5.5               2.4                3.8               1.1   
81                5.5               2.4                3.7               1.0   
82                5.8               2.7                3.9               1.2   
83                6.0               2.7                5.1               1.6   
84                5.4               3.0                4.5               1.5   
85                6.0               3.4                4.5               1.6   
86                6.7               3.1                4.7               1.5   
87                6.3               2.3                4.4               1.3   
88                5.6               3.0                4.1               1.3   
89  

#### Applying train_test_split for training the dataset

In [7]:
X = iris.data
Y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3)

#### Applying SVM

In [8]:
model = SVC(kernel='rbf', C=10, gamma='auto')
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

1.0

#### Using kfold cross validation

In [10]:
cross_val_score(SVC(kernel='linear', C=10, gamma='auto'), X, Y, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [11]:
cross_val_score(SVC(kernel='rbf', C=10, gamma='auto'), X, Y, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [12]:
cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'), X, Y, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

#### Using GridSearchCV for SVM

In [14]:
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval, C=cval, gamma='auto'), X, Y, cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)

avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [16]:
GCV = GridSearchCV(SVC(gamma='auto'), {
    'C': [1, 10, 20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)

GCV.fit(X, Y)
GCV.cv_results_

{'mean_fit_time': array([0.0029985 , 0.00259829, 0.00239887, 0.00179996, 0.00239782,
        0.00179896]),
 'std_fit_time': array([1.02934995e-06, 7.99059916e-04, 1.01828075e-03, 7.47037107e-04,
        4.90143937e-04, 3.99638773e-04]),
 'mean_score_time': array([0.00259976, 0.00139899, 0.00099878, 0.0009984 , 0.00099926,
        0.0007997 ]),
 'std_score_time': array([7.99395451e-04, 4.90018253e-04, 8.44957597e-07, 2.98775677e-06,
        6.32108175e-04, 7.47768035e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [17]:
df_cv_result = pd.DataFrame(GCV.cv_results_)
df_cv_result

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002998      0.000001         0.002600    7.993955e-04       1   
1       0.002598      0.000799         0.001399    4.900183e-04       1   
2       0.002399      0.001018         0.000999    8.449576e-07      10   
3       0.001800      0.000747         0.000998    2.987757e-06      10   
4       0.002398      0.000490         0.000999    6.321082e-04      20   
5       0.001799      0.000400         0.000800    7.477680e-04      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [18]:
df_cv_result[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [19]:
dir(GCV)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_

In [20]:
GCV.best_score_

0.9800000000000001

In [21]:
GCV.best_params_

{'C': 1, 'kernel': 'rbf'}

In [22]:
rs = RandomizedSearchCV(SVC(gamma='auto'), {
    'C' : [1, 10, 20],
    'kernel': ['rbf','linear']
},
cv=5,
return_train_score=False,
n_iter=2
)

rs.fit(X, Y)
df_cv_result_RSCV =  pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]
df_cv_result_RSCV

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      20          rbf         0.966667

#### Choosing best model using GridSearchCV

In [23]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'randomforest':{
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1, 5, 10]
        }
    },
    'logisticregression':{
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params' : {
            'C': [1, 5, 10]
        }
    }
}

In [24]:
scores = []

for model_name, mp in model_params.items():
    clf_GCV = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf_GCV.fit(X, Y)
    scores.append({
        'model': model_name,
        'best_score': clf_GCV.best_score_,
        'best_params': clf_GCV.best_params_
    })

In [25]:
df_clf_GCV = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df_clf_GCV

model  best_score                best_params
0                 svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        randomforest    0.960000       {'n_estimators': 10}
2  logisticregression    0.966667                   {'C': 5}